import Head from "next/head";
import { Inter } from "@next/font/google";
// import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const mainStyles = {
    display: "flex",
    height: "100vh",
    flexDirection: "column",
    placeContent: "center",
    textAlign: "center",
    letterSpacing: "1px",
    fontSize: "clamp(1.2rem, 4vw, 1.8rem)",
    fontFamily: inter,
  };
  return (
    <>
      <Head>
        <title>Javaman Broadway</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main style={mainStyles}>
        <h3>Java Man</h3>
        <h1>Coming Soon</h1>
      </main>
    </>
  );
}
